# Generated by Django 3.2.6 on 2021-08-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_data', models.DateTimeField(auto_now_add=True)),
                ('end_data', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
